#+FILETAGS: :feedback:
* Feedback Mechanism Module
  feedback mechanism consist of:
  - speaker
  - led
* LED
** Setup
*** Physical Hardware
    | LED  | PI     |
    |------+--------|
    | +ve  | 5v     |
    | -ve  | ground |
    | data | pin 18 |
*** Software Installation
    - build tools, may be able to skip
      #+BEGIN_SRC sh
        sudo apt-get install build-essential python-dev python-pip unzip wget scons swig
      #+END_SRC
    - installation
      #+BEGIN_SRC sh
        sudo pip install rpi_ws281x
      #+END_SRC
*** how to use?
    - this is helpful https://github.com/jgarff/rpi_ws281x/blob/master/python/neopixel.py
    - examples https://github.com/jgarff/rpi_ws281x/tree/master/python/examples
      - strand test example useful https://github.com/jgarff/rpi_ws281x/blob/master/python/examples/strandtest.py
    #+BEGIN_SRC python
      from feedback_mechanism import led
      from neopixel import *

      # self defined colors
      # def Color(red, green, blue, white = 0):
      unicorn = Color(255,0,0,255)

      # you need to hold on to the strip object to tell it which led to change
      # take a look at neopixel.py for help 
      strip = led.init()
      # def setPixelColor(self, n, color):
      strip.setPixelColor(1, unicorn)
      # def setPixelColorRGB(self, n, red, green, blue, white = 0):
      strip.setPixelColorRGB(1, 255, 0, 0, 255)
      # def setBrightness(self, brightness):
      # def getBrightness(self):
    #+END_SRC
* Speaker
** Setup
   We would go with the physical method first. However I have read
   some blog post saying that its not possible to play music and
   control the leds at the same time. This is due to the digital logic
   output is based on the BCM-2835. If it cannot work then we have to
   use bluetooth to pair it to the amplifier
   - might need to blacklist the BMC-2835
*** Physical Hardware
    - connect RCA jack on raspberrypi to TDA7492P amplifier
    - wire the speaker to the amplifier and bam.
*** Software Installation
    - I have read some tutorials that say need to disable audio for
    WS2812 to work, not sure
    - also audio might be routing through HDMI could try this to solve
      #+BEGIN_SRC sh
        raspi-config
      #+END_SRC
      - Select 7 Advanced Options, then Audio.
      - Select "Force 3.5mm ('headphone') jack".
      - Then "OK".
*** Bluetooth Pairing
    - could probably use gui but if that fails we can use this https://raspberrypi.stackexchange.com/questions/53408/automatically-connect-trusted-bluetooth-speaker/76288
